name: publish ghcr

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 */7 1-12 *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Verified commit check
        uses: nadock/verified_commits_check@v1
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      -
        name: Build
        id: docker_build
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${{ github.repository_owner }}/aiosre:latest \
          -t ghcr.io/${{ github.repository_owner }}/aiosre:latest-ci \
          --push \
          .
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
